## Numpy : Practice Problems 1

##### write a numpy program to get the numpy version and show numpy build configuration.

In [2]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\palas\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


##### create a null vector of size 10 but the fifth value which is 1.

In [9]:
z = np.zeros(10,dtype=int)
z[4]=1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

##### create a vector with vallues ranging from 10 to 49

In [11]:
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##### create two arrays and stack them vertically

In [17]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(np.vstack((a,b)))

[[7 8 1]
 [3 8 2]
 [6 2 9]
 [6 8 7]
 [7 3 4]
 [6 4 5]]


##### reverse a vector(first element becomes last

In [24]:
print(a)
np.flip(a)

[[7 8 1]
 [3 8 2]
 [6 2 9]]


array([[9, 2, 6],
       [2, 8, 3],
       [1, 8, 7]])

##### create a 3X3 matrix with values ranging from 0 to 8.

In [25]:
m_a = np.random.randint(0,9,(3,3))
m_a

array([[2, 8, 8],
       [8, 8, 5],
       [3, 7, 8]])

##### find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

##### create a 10X10 array with random values and find the minimum and maximum values.

In [40]:
arr=np.random.randint(0,100,(10,10))
print(arr.max())
print(arr.min())
print(arr)

99
1
[[ 4 37 25 41 53 75 31  4 19 89]
 [57 69 34  7 70  4 86 43 89 75]
 [ 7 94 53 86 72 60 84 22 30 42]
 [33 80 71 89  6  6 73 25 75 12]
 [ 5 40 65 79 63 96 92 25 55 64]
 [22 70 81 10  4 76 59 55 43 36]
 [99 94 84 52  6 97 45 46 32 35]
 [95 31 43 37 61 14 35 75 11 47]
 [89 78 30 23 65 41 65 19 81 79]
 [ 7 45 11 12 26  4  5 79  1 80]]


##### create a random vector of size 30 and find the mean value

In [42]:
m = np.random.randint(1,50,(6,5))
print(np.mean(m))

25.766666666666666


##### create a 2D array with 1 on the border and 0 inside

In [43]:
oneborder = np.ones((10,10))
oneborder[1:-1,1:-1]=0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


##### how to add border filled with zeros around an existing array

In [44]:
border = np.random.randint(1,100,(10,10))
border[1:-1,1:-1]=0
print(border
     )

[[24 67 97 37 17 89 73 69 60 28]
 [82  0  0  0  0  0  0  0  0 73]
 [41  0  0  0  0  0  0  0  0 35]
 [85  0  0  0  0  0  0  0  0 73]
 [ 5  0  0  0  0  0  0  0  0 20]
 [42  0  0  0  0  0  0  0  0 76]
 [41  0  0  0  0  0  0  0  0 11]
 [70  0  0  0  0  0  0  0  0 43]
 [79  0  0  0  0  0  0  0  0 63]
 [40 21 48 52 13  5 88 57 37 22]]


##### create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [48]:
np.diag((0,1,2,3,4,5))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

##### create a 5X5 matrix with random values and normalize it.

In [53]:
x = np.random.rand(5,5)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print(x)

[[0.6288158  0.88717797 0.72678783 0.17075448 0.59237632]
 [0.29679227 0.09169135 0.25083141 0.         0.73753194]
 [0.91278847 0.8055184  0.88059217 0.38383453 0.70311322]
 [0.55329863 0.12645497 0.01416934 0.75809536 0.14415969]
 [0.53246137 1.         0.32035221 0.7422658  0.07367082]]


##### how to find common values between two arrays

##### consider a generator function that generates 10 intergers and use it to build an array 

In [58]:
def generate():
   for n in range(15):
       yield n
nums = np.fromiter(generate(),dtype=float,count=-1)
print("New array:")
print(nums)

New array:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


##### Subtract the mean of each row of a matrix

In [62]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
x_mean = np.mean(x)
x=x-x_mean
x

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

##### considerind two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator.

##### write a numpy program to create a vector of length 10 with values  evenly distributed between 5 and 50

In [65]:
n = np.random.randint(5,50,(2,5))
n

array([[27, 29, 30,  7, 30],
       [29, 18, 16, 27, 15]])