## numpy practice problems 3

In [1]:
import numpy as np

##### find dot product of two arrays

In [4]:
a=np.array([2j,3j])
b=np.array([2j,3j])
print(np.vdot(a,b))

(13+0j)


##### create two array of 2-D and find the dot product of it.

In [5]:
x=np.array([[1j,2j],[4j,5j]])
y=np.array([[6j,5j],[8j,3j]])
print(np.vdot(x,y))

(63+0j)


##### find the vector product of given array

In [6]:
np.cross(x,y)

array([ 7.+0.j, 28.+0.j])

##### first create given array without using direcr value instead use numpy utilities and then find inner product for given array

In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
print(np.inner(a,b))

[[ 32  50]
 [ 77 122]]


##### using given two array try to print out 3rd given array

##### solve the system of equations 

In [23]:
a=np.array([[3,1],
           [1,2]])
b=np.array([9,8])
print(np.dot(np.linalg.inv(a),b))

[2. 3.]


##### check the follwing solutions is right or wrong using numpy utilities

In [11]:
x=np.array([[2,3],
           [3,1]])
y=np.array([8,5])
print(np.dot(np.linalg.inv(x),y))

[1. 2.]


##### write a program to add to arrays of different shapes

In [12]:
m_a=np.array([10,20,30])
m_b=np.array([10])
m_a+m_b

array([20, 30, 40])

##### create a 3X3 array and finds its diagonal using numpy utilities

In [14]:
print(a)
print('----------------')
print(np.diag(a))

[[3 1]
 [1 2]]
----------------
[3 2]


##### now find anti-diagonal in previous queestion using horizontal and vector flip

In [24]:
print(a)
print('------')
print(np.fliplr(a).diagonal())

[[3 1]
 [1 2]]
------
[1 1]
