## numpy practice problem 2

In [4]:
import numpy as np

##### create an array and find the sum of it

In [8]:
np.random.seed(1)
a = np.random.randint(1,100,(3,3))
a.sum()

378

##### find sin of given array

In [9]:
np.sin(a)

array([[ 0.29636858,  0.42016704, -0.67677196],
       [-0.54402111,  0.56610764, -0.2794155 ],
       [-0.99388865,  0.82682868, -0.96139749]])

##### find the mean of matrix along the row and column

In [10]:
# for columns
print(np.mean(a,axis=0))
# for rows 
print(np.mean(a,axis=1))

[42.66666667 51.33333333 32.        ]
[41.33333333 30.66666667 54.        ]


##### find the standard deviation of the given array

In [16]:
np.std(a)

29.612309752683746

##### find the transpose of the matrix

In [17]:
print(a)
a.T

[[38 13 73]
 [10 76  6]
 [80 65 17]]


array([[38, 10, 80],
       [13, 76, 65],
       [73,  6, 17]])

##### Create an array of 3*3 and find index of max along both axis

In [22]:
# for columns 
print(np.argmax(a,axis=0))
# for rows
print(np.argmax(a,axis=1))

[2 1 0]
[2 1 0]


In [5]:
np.random.seed(2)
m_a=np.random.randint(1,10,(3,3))
m_b=np.random.randint(1,10,(3,3))
print(m_a)
print('-----------')
print(m_b)
print('-----------')
print(m_a+m_b)

[[9 9 7]
 [3 9 8]
 [3 2 6]]
-----------
[[5 5 6]
 [8 4 7]
 [5 4 8]]
-----------
[[14 14 13]
 [11 13 15]
 [ 8  6 14]]


##### find the max element along axis=0 and axis=1

In [32]:
# max in axis =0
print(np.max(m_a,axis=0))
print(np.max(m_a,axis=1))

[9 9 8]
[9 9 6]


##### write a program to add two arrays of different shapes

In [1]:
# 10,11

##### calculate multiplication of transpose and matrix itself of a 3X3 matrix

In [7]:
print(np.dot(m_a.T,m_a))

[[ 99 114 105]
 [114 166 147]
 [105 147 149]]


##### find the solution of the given equation

In [18]:
A=np.array([[2,5],[4,3]])
B=np.array([8,1])
print(np.dot(np.linalg.inv(A),B))

[-1.35714286  2.14285714]


##### find the rank,trace,inverse,determinant of a given matrix

In [24]:
x=np.array([[1,1,1],[2,2,2],[3,3,3]])
# trace is the sum of its diagonal elements
# 1.
print(np.linalg.matrix_rank(x))
# 2.
print(np.trace(x))
# 3.
# print(np.linalg.inv(x))
# since the determinant is zero so no inverse is possible
# 4.
print(np.linalg.det(x))

1
6
0.0


##### find the cube of matrix

In [26]:
np.dot(np.dot(x,x),x)

array([[ 36,  36,  36],
       [ 72,  72,  72],
       [108, 108, 108]])